"""Add first login password change flag

Revision ID: 7b9047396b45
Revises: a7a625823b7b
Create Date: 2026-09-16 17:20:18.926093

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7b9047396b45"
down_revision = "a7a625823b7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "must_change_password",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("must_change_password")

    # ### end Alembic commands ###
