"""add publisher field to book

Revision ID: 7c61065c3c94
Revises: 9d04f19e19a7
Create Date: 2026-09-02 17:37:54.837445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c61065c3c94'
down_revision = '9d04f19e19a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('publisher')

    # ### end Alembic commands ###
