"""add active prefix to menus

Revision ID: 975455d7b0e7
Revises: 991bbdfdb70a
Create Date: 2026-09-11 18:14:52.636324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975455d7b0e7'
down_revision = '991bbdfdb70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_prefix', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_column('active_prefix')

    # ### end Alembic commands ###
