"""Add user member relationship

Revision ID: 991bbdfdb70a
Revises: 2bc63353ca1c
Create Date: 2026-09-10 15:09:52.481021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991bbdfdb70a'
down_revision = '2bc63353ca1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_member_user_id', ['user_id'])
        batch_op.create_foreign_key('fk_member_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint('fk_member_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('uq_member_user_id', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
